### ISSUE TITLE
Keepalive? 

### ISSUE THREAD

**Issue by lin-ycv** [ImtsSrl/KUKAVARPROXY#11]
What is the method for keeping the tcp connection alive? I tried configuring keepalive for my tcpclient, but keepalive only kicks in after 2 hours, whereas kukavarproxy times out after 30 seconds.

**Comment by dddomodossola** [comment]
Hello @v-xup6 ,
You can consider to read a robot variable with a predefined interval. Maybe $ov_pro every 10 seconds.
Regards

**Comment by lin-ycv** [comment]
@dddomodossola simple solution, thanks.
